<?php include('header.php') ?>
<?php include('section_detail-image.php') ?>
<?php include('section_detail-video.php') ?>
<?php include('section_detail-needs.php') ?>
<?php include('section_detail-info.php') ?>
<?php include('section_detail-gallery.php') ?>
<?php include('section_detail-comments.php') ?>
<?php include('modal_donation.php') ?>
<?php include('modal_cooperation.php') ?>
<?php include('footer.php') ?>